LekplatsWebApp/LekplatsWebApp/Controllers/LekplatserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LekplatsWebApp.Controllers
{
    public class LekplatserController : Controller
    {
        LekplatsService.LekplatsServiceClient klient = new LekplatsService.LekplatsServiceClient();
        public ActionResult Index()
        {
            List<string> allaOmråden = klient.GetAllaOmråden().ToList();
            allaOmråden.Sort();

            //Alla lekplatser från ett område ligger i sin egen array och alla områdes-arrayer läggs in i en lista.
            List<LekplatsService.LekplatsFullständigData[]> allaLekplatserSorterade = new List<LekplatsService.LekplatsFullständigData[]>();
            foreach (var område in allaOmråden)
            {
                LekplatsService.LekplatsFullständigData[] lekplatserFrånOmråde = klient.GetLekplatserFrånOmråde(område);
                //Om arrayen är tom finns det inga lekplatser i det området
                if (lekplatserFrånOmråde.Length > 0)
                {
                    allaLekplatserSorterade.Add(lekplatserFrånOmråde);
                }
            }
            return View(allaLekplatserSorterade);
        }

        public ActionResult Lekplats(int? lekplatsId)
        {
            if (!lekplatsId.HasValue)
            {
                return RedirectToAction("Index");
            }
            //Visar en specifik lekplats

            LekplatsService.LekplatsFullständigData lekplats = klient.GetLekplatsData(Convert.ToInt32(lekplatsId));

            return View(lekplats);
        }

        [HttpGet]
        public ActionResult GeBetyg(int? id)
        {
            //Hantering för om felaktigt id anges i url

            if (!id.HasValue)
            {
                return RedirectToAction("Index");
            }
            //Visar vyn för att lämna ett betyg

            LekplatsService.LekplatsFullständigData lekplatsAttBetygsätta = new LekplatsService.LekplatsFullständigData();

            lekplatsAttBetygsätta = klient.GetLekplatsData(Convert.ToInt32(id));

            return View(lekplatsAttBetygsätta);
        }
        [HttpPost]
        public ActionResult GeBetyg(int id, int skoj, int ren, int trygg)
        {
            LekplatsService.IndividuelltBetygData sattBetyg = new LekplatsService.IndividuelltBetygData();
            sattBetyg.skojfaktorBetyg = skoj;
            sattBetyg.renlighetBetyg = ren;
            sattBetyg.trygghetBetyg = trygg;
            sattBetyg.lekplatsId = id;

            bool betygStatus = klient.SättBetyg(sattBetyg);
            Console.WriteLine(betygStatus);
            ViewBag.b = "Tack för ditt omdöme!";

            return RedirectToAction("Lekplats", new { lekplatsId = id });

        }

    }
}

LekplatsWebApp/LekplatsWebApp/Views/Lekplatser/GeBetyg.cshtml
@model LekplatsWebApp.LekplatsService.LekplatsFullständigData

@{
    ViewBag.Title = "GeBetyg";
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
}

    <div>
        <div Id="GeIndiviBetyg" class="form-style-8 backgroundBild">
            <h2 class="">Vad tycker du om lekplatsen @Html.DisplayFor(m => m.namn)?</h2>
            @using (Html.BeginForm())
            {<div class="">
                    <div class="cont">
                        <h1>Skojfaktor</h1>
                        <div class="stars">

                            <input class="star star-5" id="skoj-5" type="radio" name="skoj" value="5" />
                            <label class="star star-5" for="skoj-5"></label>
                            <input class="star star-4" id="skoj-4" type="radio" name="skoj" value="4" />
                            <label class="star star-4" for="skoj-4"></label>
                            <input class="star star-3" id="skoj-3" type="radio" name="skoj" value="3" />
                            <label class="star star-3" for="skoj-3"></label>
                            <input class="star star-2" id="skoj-2" type="radio" name="skoj" value="2" />
                            <label class="star star-2" for="skoj-2"></label>
                            <input class="star star-1" id="skoj-1" type="radio" name="skoj" value="1" />
                            <label class="star star-1" for="skoj-1"></label>

                        </div>

                        <h1>Renlighet</h1>
                        <div class="stars">

                            <input class="star star-5" id="ren-5" type="radio" name="ren" value="5" />
                            <label class="star star-5" for="ren-5"></label>
                            <input class="star star-4" id="ren-4" type="radio" name="ren" value="4" />
                            <label class="star star-4" for="ren-4"></label>
                            <input class="star star-3" id="ren-3" type="radio" name="ren" value="3" />
                            <label class="star star-3" for="ren-3"></label>
                            <input class="star star-2" id="ren-2" type="radio" name="ren" value="2" />
                            <label class="star star-2" for="ren-2"></label>
                            <input class="star star-1" id="ren-1" type="radio" name="ren" value="1" />
                            <label class="star star-1" for="ren-1"></label>

                        </div>

                        <h1>Trygghet</h1>
                        <div class="stars">

                            <input class="star star-5" id="trygg-5" type="radio" name="trygg" value="5" />
                            <label class="star star-5" for="trygg-5"></label>
                            <input class="star star-4" id="trygg-4" type="radio" name="trygg" value="4" />
                            <label class="star star-4" for="trygg-4"></label>
                            <input class="star star-3" id="trygg-3" type="radio" name="trygg" value="3" />
                            <label class="star star-3" for="trygg-3"></label>
                            <input class="star star-2" id="trygg-2" type="radio" name="trygg" value="2" />
                            <label class="star star-2" for="trygg-2"></label>
                            <input class="star star-1" id="trygg-1" type="radio" name="trygg" value="1" />
                            <label class="star star-1" for="trygg-1"></label>

                        </div>
                        @Html.HiddenFor(m => m.lekplatsId)
                    </div>
                        <input type="submit" class="button" value="Skicka" />

                </div>}
        </div>
        <br />
        <div><a class="button" href="@Url.Action("Index", "Lekplatser")">Gå tillbaka till alla Lekplatser</a></div>

    </div>

LekplatsWebApp/LekplatsWebApp/Views/Lekplatser/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
}
@model IEnumerable<LekplatsWebApp.LekplatsService.LekplatsFullständigData[]>



<div id="bodyAsTable">
<div class="sideNavbar">
    <a id="to-top" href="#">Välj område</a>
        @foreach (var lekplatserFrånOmrådeArray in Model)
        {
            <a href="#@lekplatserFrånOmrådeArray[0].område">@lekplatserFrånOmrådeArray[0].område</a>
        }
    </div>

    <div id="allaLekplatser">
        @foreach (var lekplatserFrånOmrådeArray in Model)
        {
            <div id="@lekplatserFrånOmrådeArray[0].område">
                <div class="omrade-titel">
                    <h1>@lekplatserFrånOmrådeArray[0].område</h1></div>
                    @for (int i = 0; i < lekplatserFrånOmrådeArray.Length; i++)
                    {
                        <div class="flip-card">
                            <div class="flip-card-inner">
                                <div class="flip-card-front">
                                    <img class="kort-bild" src="https://www.trollhattan.se/globalassets/bilder/bygga-bo-och-miljo/stadsbyggnad/lekplatser/skrotnisse/skrotnisses-lekplats_toppbild.jpg" alt="Macken" style="width:300px; height:150px;">
                                    <div class="bildtext"><h2>@lekplatserFrånOmrådeArray[i].namn</h2></div>
                                    <div class="medelBetyg"><h2><span class="star star-3">Betyg: </span>@lekplatserFrånOmrådeArray[i].medelbetyg.totalMedelbetyg</h2></div>
                                </div>
                                <div class="flip-card-back">
                                    <h2>@lekplatserFrånOmrådeArray[i].namn</h2>
                                    <form action="@Url.Action("Lekplats", "Lekplatser")" method="get">
                                        <input type="hidden" name="lekplatsId" value="@lekplatserFrånOmrådeArray[i].lekplatsId" />
                                        <input type="submit" class="visaLekplats" value="Visa lekplats" />
                                    </form>
                                </div>
                            </div>
                        </div>
                    }
                </div>
        }
    </div>
</div>

LekplatsWebApp/LekplatsWebApp/Views/Lekplatser/Lekplats.cshtml
@model LekplatsWebApp.LekplatsService.LekplatsFullständigData

@{
    ViewBag.Title = "Lekplats";
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
}

<h2 class="lekplats-titel">@Html.DisplayFor(m => m.namn)</h2>
<p><span class="boldText">Område:</span> @Html.DisplayFor(m => m.område)</p>

<div class="lekplatsinfo">
    <div class="bildspel-content" style="max-width:500px; display:inline-block;">
        <img class="bildspel" src="https://www.trollhattan.se/globalassets/bilder/bygga-bo-och-miljo/stadsbyggnad/lekplatser/lextorpsparken.w.jpg" style="width:100%">
        <img class="bildspel" src="https://www.trollhattan.se/globalassets/bilder/bygga-bo-och-miljo/stadsbyggnad/lekplatser/lextorpsparken.w2.jpg" style="width:100%">
        <img class="bildspel" src="https://www.trollhattan.se/globalassets/bilder/bygga-bo-och-miljo/stadsbyggnad/lekplatser/lextorpsparken.w1.jpg" style="width:100%">
    </div>

    <br /><br />

    <div class="infolistor">
        <h3>Beskrivning</h3>
        <p style="text-align:left;">
            @Html.DisplayFor(m => m.beskrivning)
        </p>
    </div>

    <br />

    <div class="infolistor">
        <div class="infoListaRad">
            <h3>Lekutrustning</h3>
            <ul class="ul-lista">
                @foreach (var utrustning in Model.lekutrustning)
                {
                    <li>@utrustning</li>
                }
            </ul>
        </div>
        <div class="infoListaRad">
            <h3>Tillgänglighet</h3>
            <ul class="ul-lista">
                @foreach (var tillgänglighet in Model.tillgänglighet)
                {
                    <li>@tillgänglighet</li>
                }
            </ul>
        </div>
        <div class="infoListaRad">
            <h3>Lämplig ålder för lekplatsen</h3>
            <p class="center"><span class="highlight">@Html.DisplayFor(m => Model.målgrupp[0]) till @Html.DisplayFor(m => Model.målgrupp[1]) år</span></p>
        </div>
    </div>
    <br />
    <div class="infolistor">
        <p class="highlight">Totalt medelbetyg: <span class="boldText"> @Html.DisplayFor(m => m.medelbetyg.totalMedelbetyg) </span> av 5</p>
        <p class="highlight">Skojfaktor:<span class="boldText"> @Html.DisplayFor(m => m.medelbetyg.skojfaktorMedelbetyg) </span> av 5</p>
        <p class="highlight">Renlighet:<span class="boldText"> @Html.DisplayFor(m => m.medelbetyg.renlighetMedelbetyg) </span> av 5</p>
        <p class="highlight">Trygghet:<span class="boldText"> @Html.DisplayFor(m => m.medelbetyg.trygghetMedelbetyg) </span> av 5</p>
        <p>Antal röster totalt:<span class="highlight"> @Html.DisplayFor(m => m.medelbetyg.antalRöster) </span></p>


        <a href="GeBetyg/@Model.lekplatsId" class="button">Ge Betyg!</a>
    </div>
    <br />
    <div class="infolistor">
        <p>Adress: <span class="boldText">@Html.DisplayFor(m => m.adress)</span></p>
    </div>
</div>
<br />
<div><a class="button" href="@Url.Action("Index", "Lekplatser")">Gå tillbaka till alla Lekplatser</a></div>

<script>
    var myIndex = 0;
    carousel();

    function carousel() {
        var i;
        var x = document.getElementsByClassName("bildspel");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) { myIndex = 1 }
        x[myIndex - 1].style.display = "block";
        setTimeout(carousel, 3000);
    }
</script>